### ISSUE TITLE
Bug in to_decimal()

### ISSUE THREAD

**Issue by Grimeton** [theory/data-types#4]
Hello,

I found a bug in to_decimal. As soon as precision is > 15 I get weird output on a 64bit OS X with perl 5.16.

Here a testdrive:

$ perl -MData::Types=:all -e '$a="5.123456789"; foreach $i (1..20) { print "I: $i\nto_decimal: " . to_decimal($a,$i) . "\n"; } '
I: 1
to_decimal: 5.1
I: 2
to_decimal: 5.12
I: 3
to_decimal: 5.123
I: 4
to_decimal: 5.1235
I: 5
to_decimal: 5.12346
I: 6
to_decimal: 5.123457
I: 7
to_decimal: 5.1234568
I: 8
to_decimal: 5.12345679
I: 9
to_decimal: 5.123456789
I: 10
to_decimal: 5.1234567890
I: 11
to_decimal: 5.12345678900
I: 12
to_decimal: 5.123456789000
I: 13
to_decimal: 5.1234567890000
I: 14
to_decimal: 5.12345678900000
I: 15
to_decimal: 5.123456789000000
I: 16
to_decimal: 5.1234567889999996
I: 17
to_decimal: 5.12345678899999957
I: 18
to_decimal: 5.123456788999999567
I: 19
to_decimal: 5.1234567889999995671
I: 20
to_decimal: 5.12345678899999956712

As to_real and to_float are identical the issue is there too.

Not sure if this is a bug in your implementation or the underlying function called.

KR,

Oliver

**Comment by theory** [comment]
That's the output of `sprintf`:

    > perl -E 'say sprintf "%.16f", 5.123456789'
    5.1234567889999996

Pretty sure it's just hitting the boundary of accuracy for 64 bits. If I force long long, it's the same:

    > perl -E 'say sprintf "%.16llf", 5.123456789'
    5.1234567889999996

If you need more accuracy, you should probably use [Math::BigFloat](https://metacpan.org/pod/Math::BigFloat), instead:

    > perl -MMath::BigFloat -E 'say Math::BigFloat->new("5.123456789")'
    5.123456789
